apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synergize-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  rules:
    - host: apps.blisstudio.online
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: synergize-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: synergize-service
spec:
  selector:
    app: synergize-apps
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergize-apps
spec:
  selector:
    matchLabels:
      app: synergize-apps
  replicas: 1
  template:
    metadata:
      labels:
        app: synergize-apps
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: synergize-apps
        image: gcr.io/synergize-test/synergize:latest
        envFrom:
        - configMapRef:
            name: syn-configmap
        ports:
        - containerPort: 5000
        # resources:
        #   requests:
        #     memory: "200Mi"
        #     cpu: "1m"
        #   limits:
        #     memory: "500Mi"
        #     cpu: "250m"